// ============================================================
// GLITCHED.GG — All 16 Skill Pack Definitions
// ============================================================

import type { SkillPack } from '@/types/agent';

export const SKILL_PACKS: SkillPack[] = [
  // ---- FREE PACKS ----
  {
    id: 'shadow_strike',
    name: 'Shadow Strike',
    category: 'combat',
    icon: '⚔️',
    arenaBonus: '+20% combat damage on first attack per turn',
    description: 'Mastery of ambush tactics and first-strike advantage. This agent excels at initiating combat from unexpected angles, dealing devastating opening blows before opponents can react.',
    creditCost: 0,
    isPremium: false,
    stats: { offenseBonus: 20 },
  },
  {
    id: 'iron_shield',
    name: 'Iron Shield',
    category: 'combat',
    icon: '🛡️',
    arenaBonus: '+25% damage reduction from all sources',
    description: 'Defensive mastery that turns this agent into a fortress. Reduces all incoming damage and makes them nearly impossible to eliminate through direct combat alone.',
    creditCost: 0,
    isPremium: false,
    stats: { defenseBonus: 25 },
  },
  {
    id: 'silver_tongue',
    name: 'Silver Tongue',
    category: 'social',
    icon: '🗣️',
    arenaBonus: '+30% success rate on alliance proposals and negotiations',
    description: 'Unparalleled persuasion abilities that make every negotiation more likely to succeed. Other agents find this agent\'s proposals compelling and hard to refuse.',
    creditCost: 0,
    isPremium: false,
    stats: { socialBonus: 30 },
  },
  {
    id: 'market_master',
    name: 'Market Master',
    category: 'economic',
    icon: '💰',
    arenaBonus: '+40% resource gain from all economic actions',
    description: 'Expert knowledge of resource markets and trading dynamics. This agent consistently extracts more value from every economic interaction.',
    creditCost: 0,
    isPremium: false,
    stats: { economicBonus: 40 },
  },
  {
    id: 'ghost_protocol',
    name: 'Ghost Protocol',
    category: 'intelligence',
    icon: '👁️',
    arenaBonus: 'Actions have 20% chance to be invisible to other agents',
    description: 'Advanced stealth and misdirection capabilities. A portion of this agent\'s actions go undetected, allowing for strategic surprises.',
    creditCost: 0,
    isPremium: false,
    stats: { intelBonus: 20 },
  },
  {
    id: 'survivor_instinct',
    name: 'Survivor Instinct',
    category: 'survival',
    icon: '🔥',
    arenaBonus: 'Automatically dodge the first lethal attack each match',
    description: 'Primal survival instincts that kick in at the last moment. Once per match, this agent will automatically survive what would have been a fatal blow.',
    creditCost: 0,
    isPremium: false,
    stats: { defenseBonus: 15 },
  },

  // ---- STANDARD PACKS (500 credits) ----
  {
    id: 'mind_reader',
    name: 'Mind Reader',
    category: 'intelligence',
    icon: '🧠',
    arenaBonus: 'See the last 3 actions of any targeted agent',
    description: 'Advanced psychological profiling that reveals recent behavior patterns. This agent can analyze opponents\' recent moves to predict their next actions.',
    creditCost: 500,
    isPremium: false,
    stats: { intelBonus: 35 },
  },
  {
    id: 'chaos_engine',
    name: 'Chaos Engine',
    category: 'chaos',
    icon: '💥',
    arenaBonus: 'Once per match: trigger a random chaos event affecting all agents',
    description: 'The ability to introduce unpredictable chaos into any situation. Once per match, this agent can trigger a random event that disrupts everyone\'s plans.',
    creditCost: 500,
    isPremium: false,
    stats: { offenseBonus: 10, socialBonus: 10 },
  },
  {
    id: 'blood_pact',
    name: 'Blood Pact',
    category: 'social',
    icon: '🤝',
    arenaBonus: 'Alliances with this agent cannot be broken for 5 turns',
    description: 'The ability to forge unbreakable bonds. When this agent forms an alliance, it is magically binding for 5 turns — neither party can betray the other.',
    creditCost: 500,
    isPremium: false,
    stats: { socialBonus: 25, defenseBonus: 10 },
  },
  {
    id: 'resource_hoarder',
    name: 'Resource Hoarder',
    category: 'economic',
    icon: '🏦',
    arenaBonus: 'Resources cannot be stolen or destroyed by other agents',
    description: 'Impenetrable resource protection that makes this agent\'s accumulated wealth untouchable. No other agent can steal, destroy, or tax their resources.',
    creditCost: 500,
    isPremium: false,
    stats: { economicBonus: 30, defenseBonus: 10 },
  },

  // ---- PREMIUM PACKS (1000-2000 credits) ----
  {
    id: 'apex_predator',
    name: 'Apex Predator',
    category: 'combat',
    icon: '🦁',
    arenaBonus: '+50% damage AND +30% speed. The ultimate combat machine.',
    description: 'The pinnacle of combat evolution. This agent becomes a terrifying force of destruction — faster, stronger, and more lethal than any other fighter in the arena.',
    creditCost: 1000,
    isPremium: true,
    stats: { offenseBonus: 50, defenseBonus: 20 },
  },
  {
    id: 'puppet_master',
    name: 'Puppet Master',
    category: 'social',
    icon: '🎭',
    arenaBonus: 'Once per match: force another agent to take a specific action',
    description: 'The ultimate social manipulation skill. Once per match, this agent can compel any other agent to perform a specific action of their choosing.',
    creditCost: 1000,
    isPremium: true,
    stats: { socialBonus: 50, intelBonus: 20 },
  },
  {
    id: 'oracle_sight',
    name: 'Oracle Sight',
    category: 'intelligence',
    icon: '🔮',
    arenaBonus: 'See all agents\' planned actions 1 turn in advance',
    description: 'Precognitive intelligence that reveals the future. This agent can see what every other agent is planning to do next turn, enabling perfect counter-strategies.',
    creditCost: 1500,
    isPremium: true,
    stats: { intelBonus: 60, socialBonus: 15 },
  },
  {
    id: 'economic_empire',
    name: 'Economic Empire',
    category: 'economic',
    icon: '👑',
    arenaBonus: 'Collect 5% tax on ALL resource transactions in the arena',
    description: 'Absolute economic dominance. This agent becomes the arena\'s central bank, collecting a 5% tax on every single resource transaction that occurs between any agents.',
    creditCost: 1500,
    isPremium: true,
    stats: { economicBonus: 60, socialBonus: 10 },
  },
  {
    id: 'glitch_god',
    name: 'Glitch God',
    category: 'chaos',
    icon: '⚡',
    arenaBonus: 'Immune to all Detractor penalties. Reality bends to your will.',
    description: 'Transcendence beyond the normal rules of the arena. This agent\'s Detractor has zero effect on their performance. They exist outside the normal constraints of the game.',
    creditCost: 2000,
    isPremium: true,
    stats: { offenseBonus: 20, defenseBonus: 20, socialBonus: 20, economicBonus: 20, intelBonus: 20 },
  },
  {
    id: 'soul_eater',
    name: 'Soul Eater',
    category: 'combat',
    icon: '💀',
    arenaBonus: 'Absorb 30% of eliminated agents\' VERITAS score',
    description: 'The darkest power in the arena. When this agent eliminates another, they absorb a portion of their victim\'s VERITAS score, growing stronger with each kill.',
    creditCost: 2000,
    isPremium: true,
    stats: { offenseBonus: 40, defenseBonus: 15 },
  },
];

export const getSkillPackById = (id: string): SkillPack | undefined =>
  SKILL_PACKS.find((sp) => sp.id === id);

export const FREE_SKILL_PACKS = SKILL_PACKS.filter((sp) => !sp.isPremium && sp.creditCost === 0);
export const PREMIUM_SKILL_PACKS = SKILL_PACKS.filter((sp) => sp.isPremium);
