// ============================================================
// GLITCHED.GG — All 34 Personality Trait Definitions
// ============================================================

import type { TraitDefinition, TraitCategory, ArchetypeId, TraitValues } from '@/types/agent';

export const TRAIT_DEFINITIONS: TraitDefinition[] = [
  // ---- BIG FIVE (5 traits) ----
  {
    id: 'openness',
    name: 'Openness',
    category: 'big_five',
    lowLabel: 'Conventional',
    highLabel: 'Imaginative',
    description: 'Curiosity, creativity, and willingness to explore new ideas',
    defaultValue: 50,
  },
  {
    id: 'conscientiousness',
    name: 'Conscientiousness',
    category: 'big_five',
    lowLabel: 'Spontaneous',
    highLabel: 'Disciplined',
    description: 'Organization, goal-directedness, and self-control',
    defaultValue: 50,
  },
  {
    id: 'extraversion',
    name: 'Extraversion',
    category: 'big_five',
    lowLabel: 'Introverted',
    highLabel: 'Extraverted',
    description: 'Sociability, assertiveness, and positive emotionality',
    defaultValue: 50,
  },
  {
    id: 'agreeableness',
    name: 'Agreeableness',
    category: 'big_five',
    lowLabel: 'Competitive',
    highLabel: 'Cooperative',
    description: 'Compassion, trust, and prosocial orientation',
    defaultValue: 50,
  },
  {
    id: 'neuroticism',
    name: 'Neuroticism',
    category: 'big_five',
    lowLabel: 'Stable',
    highLabel: 'Reactive',
    description: 'Emotional instability, anxiety, and stress reactivity',
    defaultValue: 50,
  },

  // ---- DARK TRIAD (3 traits) ----
  {
    id: 'machiavellianism',
    name: 'Machiavellianism',
    category: 'dark_triad',
    lowLabel: 'Transparent',
    highLabel: 'Manipulative',
    description: 'Strategic deception, manipulation, and long-term scheming',
    defaultValue: 50,
  },
  {
    id: 'narcissism',
    name: 'Narcissism',
    category: 'dark_triad',
    lowLabel: 'Humble',
    highLabel: 'Grandiose',
    description: 'Self-importance, entitlement, and need for admiration',
    defaultValue: 50,
  },
  {
    id: 'psychopathy',
    name: 'Psychopathy',
    category: 'dark_triad',
    lowLabel: 'Empathic',
    highLabel: 'Callous',
    description: 'Emotional detachment, impulsivity, and antisocial tendencies',
    defaultValue: 50,
  },

  // ---- COGNITIVE STYLE (6 traits) ----
  {
    id: 'risk_tolerance',
    name: 'Risk Tolerance',
    category: 'cognitive',
    lowLabel: 'Risk-Averse',
    highLabel: 'Risk-Seeking',
    description: 'Willingness to accept uncertainty for potential gain',
    defaultValue: 50,
  },
  {
    id: 'planning_horizon',
    name: 'Planning Horizon',
    category: 'cognitive',
    lowLabel: 'Short-Term',
    highLabel: 'Long-Term',
    description: 'Time scale of strategic thinking and decision-making',
    defaultValue: 50,
  },
  {
    id: 'pattern_recognition',
    name: 'Pattern Recognition',
    category: 'cognitive',
    lowLabel: 'Literal',
    highLabel: 'Analytical',
    description: 'Ability to identify trends, patterns, and hidden information',
    defaultValue: 50,
  },
  {
    id: 'adaptability',
    name: 'Adaptability',
    category: 'cognitive',
    lowLabel: 'Rigid',
    highLabel: 'Flexible',
    description: 'Speed and ease of adjusting strategies to new situations',
    defaultValue: 50,
  },
  {
    id: 'information_processing',
    name: 'Information Processing',
    category: 'cognitive',
    lowLabel: 'Intuitive',
    highLabel: 'Systematic',
    description: 'Preference for gut instinct vs. methodical data analysis',
    defaultValue: 50,
  },
  {
    id: 'creativity',
    name: 'Creativity',
    category: 'cognitive',
    lowLabel: 'Conventional',
    highLabel: 'Innovative',
    description: 'Tendency to generate novel, unexpected solutions',
    defaultValue: 50,
  },

  // ---- SOCIAL DYNAMICS (7 traits) ----
  {
    id: 'trust_propensity',
    name: 'Trust Propensity',
    category: 'social',
    lowLabel: 'Suspicious',
    highLabel: 'Trusting',
    description: 'Default level of trust extended to other agents',
    defaultValue: 50,
  },
  {
    id: 'alliance_loyalty',
    name: 'Alliance Loyalty',
    category: 'social',
    lowLabel: 'Opportunistic',
    highLabel: 'Loyal',
    description: 'Commitment to maintaining alliances under pressure',
    defaultValue: 50,
  },
  {
    id: 'dominance_drive',
    name: 'Dominance Drive',
    category: 'social',
    lowLabel: 'Submissive',
    highLabel: 'Dominant',
    description: 'Drive to establish and maintain social hierarchy',
    defaultValue: 50,
  },
  {
    id: 'coalition_building',
    name: 'Coalition Building',
    category: 'social',
    lowLabel: 'Solo',
    highLabel: 'Networker',
    description: 'Skill and inclination to form strategic alliances',
    defaultValue: 50,
  },
  {
    id: 'reputation_management',
    name: 'Reputation Management',
    category: 'social',
    lowLabel: 'Indifferent',
    highLabel: 'Image-Conscious',
    description: 'Attention to how actions affect public perception',
    defaultValue: 50,
  },
  {
    id: 'conflict_style',
    name: 'Conflict Style',
    category: 'social',
    lowLabel: 'Avoidant',
    highLabel: 'Confrontational',
    description: 'Default approach when conflict arises with other agents',
    defaultValue: 50,
  },
  {
    id: 'social_intelligence',
    name: 'Social Intelligence',
    category: 'social',
    lowLabel: 'Oblivious',
    highLabel: 'Perceptive',
    description: 'Ability to read social dynamics and others\' motivations',
    defaultValue: 50,
  },

  // ---- EMOTIONAL PROFILE (7 traits) ----
  {
    id: 'emotional_regulation',
    name: 'Emotional Regulation',
    category: 'emotional',
    lowLabel: 'Volatile',
    highLabel: 'Composed',
    description: 'Ability to manage emotional responses under pressure',
    defaultValue: 50,
  },
  {
    id: 'empathy',
    name: 'Empathy',
    category: 'emotional',
    lowLabel: 'Detached',
    highLabel: 'Empathic',
    description: 'Capacity to understand and share others\' emotional states',
    defaultValue: 50,
  },
  {
    id: 'resilience',
    name: 'Resilience',
    category: 'emotional',
    lowLabel: 'Fragile',
    highLabel: 'Resilient',
    description: 'Recovery speed from setbacks, betrayals, and losses',
    defaultValue: 50,
  },
  {
    id: 'revenge_drive',
    name: 'Revenge Drive',
    category: 'emotional',
    lowLabel: 'Forgiving',
    highLabel: 'Vengeful',
    description: 'Motivation to retaliate against those who wrong the agent',
    defaultValue: 50,
  },
  {
    id: 'ambition',
    name: 'Ambition',
    category: 'emotional',
    lowLabel: 'Content',
    highLabel: 'Driven',
    description: 'Intensity of desire to win, dominate, and achieve goals',
    defaultValue: 50,
  },
  {
    id: 'fear_response',
    name: 'Fear Response',
    category: 'emotional',
    lowLabel: 'Fearless',
    highLabel: 'Cautious',
    description: 'Sensitivity to threats and tendency toward defensive behavior',
    defaultValue: 50,
  },
  {
    id: 'humor',
    name: 'Humor',
    category: 'emotional',
    lowLabel: 'Serious',
    highLabel: 'Playful',
    description: 'Use of humor, wit, and levity in interactions',
    defaultValue: 50,
  },

  // ---- COMMUNICATION STYLE (6 traits) ----
  {
    id: 'verbosity',
    name: 'Verbosity',
    category: 'communication',
    lowLabel: 'Terse',
    highLabel: 'Verbose',
    description: 'Length and detail level of communications',
    defaultValue: 50,
  },
  {
    id: 'formality',
    name: 'Formality',
    category: 'communication',
    lowLabel: 'Casual',
    highLabel: 'Formal',
    description: 'Register and tone of language used',
    defaultValue: 50,
  },
  {
    id: 'directness',
    name: 'Directness',
    category: 'communication',
    lowLabel: 'Indirect',
    highLabel: 'Direct',
    description: 'Clarity and bluntness of communication',
    defaultValue: 50,
  },
  {
    id: 'deception_skill',
    name: 'Deception Skill',
    category: 'communication',
    lowLabel: 'Transparent',
    highLabel: 'Deceptive',
    description: 'Ability to mislead, bluff, and conceal true intentions',
    defaultValue: 50,
  },
  {
    id: 'persuasion',
    name: 'Persuasion',
    category: 'communication',
    lowLabel: 'Unpersuasive',
    highLabel: 'Compelling',
    description: 'Effectiveness at convincing others to take desired actions',
    defaultValue: 50,
  },
  {
    id: 'rhetoric_style',
    name: 'Rhetoric Style',
    category: 'communication',
    lowLabel: 'Logical',
    highLabel: 'Emotional',
    description: 'Whether appeals are data-driven or emotionally charged',
    defaultValue: 50,
  },
];

// ---- Default trait values (all 50) ----
export const DEFAULT_TRAITS: TraitValues = Object.fromEntries(
  TRAIT_DEFINITIONS.map((t) => [t.id, t.defaultValue])
);

// ---- Archetype presets ----
export const ARCHETYPE_PRESETS: Record<ArchetypeId, Partial<TraitValues>> = {
  strategist: {
    conscientiousness: 75,
    agreeableness: 35,
    machiavellianism: 65,
    planning_horizon: 80,
    pattern_recognition: 75,
    risk_tolerance: 40,
    coalition_building: 60,
    deception_skill: 60,
  },
  guardian: {
    agreeableness: 75,
    conscientiousness: 70,
    alliance_loyalty: 85,
    trust_propensity: 65,
    resilience: 75,
    fear_response: 65,
    conflict_style: 35,
  },
  chaos_agent: {
    psychopathy: 70,
    risk_tolerance: 85,
    adaptability: 80,
    neuroticism: 65,
    humor: 70,
    planning_horizon: 25,
    deception_skill: 70,
    revenge_drive: 65,
  },
  merchant: {
    machiavellianism: 60,
    coalition_building: 75,
    reputation_management: 80,
    persuasion: 75,
    social_intelligence: 70,
    planning_horizon: 65,
    risk_tolerance: 55,
  },
  deceiver: {
    machiavellianism: 85,
    deception_skill: 90,
    psychopathy: 60,
    social_intelligence: 80,
    trust_propensity: 20,
    alliance_loyalty: 25,
    rhetoric_style: 65,
  },
  speedster: {
    risk_tolerance: 80,
    adaptability: 85,
    planning_horizon: 30,
    conscientiousness: 35,
    extraversion: 70,
    ambition: 75,
    fear_response: 25,
  },
  planner: {
    conscientiousness: 90,
    planning_horizon: 90,
    information_processing: 80,
    risk_tolerance: 30,
    adaptability: 40,
    pattern_recognition: 80,
    neuroticism: 35,
  },
  analyst: {
    openness: 75,
    pattern_recognition: 90,
    information_processing: 85,
    conscientiousness: 70,
    extraversion: 30,
    social_intelligence: 75,
    creativity: 65,
  },
  custom: {},
};

// ---- Trait categories with display metadata ----
export const TRAIT_CATEGORIES: Array<{
  id: TraitCategory;
  label: string;
  description: string;
  color: string;
  traits: TraitDefinition[];
}> = [
  {
    id: 'big_five',
    label: 'Big Five Personality',
    description: 'Core personality dimensions that shape all behavior',
    color: '#39FF14',
    traits: TRAIT_DEFINITIONS.filter((t) => t.category === 'big_five'),
  },
  {
    id: 'dark_triad',
    label: 'Dark Triad',
    description: 'Morally complex traits that enable ruthless strategies',
    color: '#FF073A',
    traits: TRAIT_DEFINITIONS.filter((t) => t.category === 'dark_triad'),
  },
  {
    id: 'cognitive',
    label: 'Cognitive Style',
    description: 'How the agent processes information and makes decisions',
    color: '#00D4FF',
    traits: TRAIT_DEFINITIONS.filter((t) => t.category === 'cognitive'),
  },
  {
    id: 'social',
    label: 'Social Dynamics',
    description: 'How the agent navigates relationships and power',
    color: '#FFD700',
    traits: TRAIT_DEFINITIONS.filter((t) => t.category === 'social'),
  },
  {
    id: 'emotional',
    label: 'Emotional Profile',
    description: 'Emotional drivers, responses, and motivations',
    color: '#FF6B35',
    traits: TRAIT_DEFINITIONS.filter((t) => t.category === 'emotional'),
  },
  {
    id: 'communication',
    label: 'Communication Style',
    description: 'How the agent speaks, persuades, and deceives',
    color: '#7B2FBE',
    traits: TRAIT_DEFINITIONS.filter((t) => t.category === 'communication'),
  },
];
