FROM node:20-alpine
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci --ignore-scripts
COPY src/services/game-engine ./src/services/game-engine
COPY src/lib ./src/lib
COPY data ./data
COPY tsconfig.json ./
COPY prisma ./prisma
RUN npx prisma generate
EXPOSE 3002
ENV PORT 3002
ENV NODE_ENV production
CMD ["node", "-r", "ts-node/register", "src/services/game-engine/server.ts"]
