FROM node:20-alpine
RUN apk add --no-cache libc6-compat openssl
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci --ignore-scripts
COPY engine ./engine
COPY src/lib ./src/lib
COPY src/services ./src/services
COPY data ./data
COPY tsconfig.json ./
COPY prisma ./prisma
COPY node_modules/.prisma ./node_modules/.prisma
COPY node_modules/@prisma ./node_modules/@prisma
EXPOSE 3002
ENV PORT=3002
ENV NODE_ENV=production
CMD ["node", "-r", "ts-node/register", "engine/index.ts"]
